# Generated by Django 3.2.6 on 2021-08-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='date_created',
            new_name='date_joined',
        ),
    ]
