# Generated by Django 3.2.6 on 2021-08-15 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210815_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='send_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
