# Generated by Django 3.2.6 on 2021-08-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20210817_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_name',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
