# Generated by Django 3.2.6 on 2021-08-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_chatroom_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='roomname',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_name',
            field=models.CharField(max_length=100),
        ),
    ]
