# Generated by Django 3.2.6 on 2021-08-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20210817_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='roomname',
            field=models.CharField(max_length=100),
        ),
    ]
